[build]
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Du kan behålla [[headers]] sektionen om du hade den för att få det att fungera
# [[headers]]
#   for = "/*"
#   [headers.values]
#     X-Frame-Options = "DENY"